# Generated by Django 4.1.3 on 2023-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="contract",
            new_name="contact",
        ),
    ]
